window.PHUC_THINH_IMPORTED_PEOPLE = [
    {
    "id": "person-director-huan",
    "name": "Đào Ngọc Huân",
    "gender": "Nam",
    "departmentId": "ban-giam-doc",
    "roleId": "giam-doc",
    "contract": "Biên chế",
    "qualification": "Đại học / Thạc sĩ",
    "phone": "",
    "address": "TP Hà Nội",
    "customFields": {},
    "createdAt": "2026-07-23T00:00:00.000Z",
    "createdBy": "Hệ thống"
},
{
    "id": "person-deputy-hien",
    "name": "Nguyễn Văn Hiện",
    "gender": "Nam",
    "departmentId": "ban-giam-doc",
    "roleId": "pho-giam-doc",
    "contract": "Biên chế",
    "qualification": "Đại học / Thạc sĩ",
    "phone": "",
    "address": "TP Hà Nội",
    "customFields": {},
    "createdAt": "2026-07-23T00:00:00.000Z",
    "createdBy": "Hệ thống"
},
{
    "id": "person-deputy-hanh",
    "name": "Nguyễn Thị Hồng Hạnh",
    "gender": "Nữ",
    "departmentId": "ban-giam-doc",
    "roleId": "pho-giam-doc",
    "contract": "Biên chế",
    "qualification": "Đại học / Thạc sĩ",
    "phone": "",
    "address": "TP Hà Nội",
    "customFields": {},
    "createdAt": "2026-07-23T00:00:00.000Z",
    "createdBy": "Hệ thống"
},
{
    "id": "person-deputy-dung",
    "name": "Tô Việt Dũng",
    "gender": "Nam",
    "departmentId": "ban-giam-doc",
    "roleId": "pho-giam-doc",
    "contract": "Biên chế",
    "qualification": "Đại học / Thạc sĩ",
    "phone": "",
    "address": "TP Hà Nội",
    "customFields": {},
    "createdAt": "2026-07-23T00:00:00.000Z",
    "createdBy": "Hệ thống"
}
    {
        "id":  "excel-s1-r11",
        "name":  "Nguyễn Thị Huyền Trang",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "Truong-phong-ke-hoach",
        "contract":  "Biên chế",
        "qualification":  "Đại học - Kiến trúc sư Quy hoạch đô thị",
        "contractTerm":  "Đến 03/01/2030",
        "contractSignedDate":  "",
        "phone":  "0962535490",
        "birthDate":  "1990-04-05",
        "start":  "",
        "salaryCoefficient":  "3",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2026-04-01",
        "address":  "Thôn Hà Hương, xã Thư Lâm-TP HN",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Trưởng phòng KHTH; Quê quán: Thôn Hà Hương, xã Thư Lâm-TP HN; Đảng viên: Có; Ngoại ngữ: Anh, B2, Anh B1; Tin học: Chứng chỉ ứng dụng thông tin cơ bản, chuẩn Thông tư 03/2014/TT-BTTTT; Ngạch/CDNN: Kỹ sư hạng III, V.05.02.07"
    },
    {
        "id":  "excel-s1-r12",
        "name":  "Nguyễn Văn Hưởng",
        "gender":  "Nam",
        "departmentId":  "ke-hoach",
        "roleId":  "Pho-phong-ke-hoach",
        "contract":  "Biên chế",
        "qualification":  "Đại học - Kiến Trúc sư kiến trúc công trình",
        "contractTerm":  "HĐLV xác định thời hạn 60 tháng)",
        "contractSignedDate":  "",
        "phone":  "0966728686",
        "birthDate":  "1986-03-13",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2028-06-12",
        "address":  "thôn Đường Nhạn, xã Thư Lâm, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Viên chức phòng KHTH; Quê quán: xã Vĩnh Thanh, TP Hà Nội; Tin học: chuẩn Thông tư 03/2014/TT-BTTTT; Ngạch/CDNN: V04.01.03"
    },
    {
        "id":  "excel-s1-r13",
        "name":  "Hoàng Thị Thùy Dung",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Biên chế",
        "qualification":  "Thạc sĩ - Thạc sỹ Quản trị kinh doanh, cử nhân kế toán",
        "contractTerm":  "HĐLV không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0989983003",
        "birthDate":  "1984-10-10",
        "start":  "",
        "salaryCoefficient":  "3.99",
        "salaryGrade":  "6/9",
        "salaryReviewDate":  "2026-11-01",
        "address":  "Nghĩa Vũ-Đông Anh-HN",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Viên chức phòng KHTH; Quê quán: thôn Phương Trạch,x ã Vĩnh Thanh-HN; Đảng viên: Có; LLCT: Sơ cấp; Tin học: chuẩn Thông tư 03/2014/TT-BTTTT; Ngạch/CDNN: 06.031"
    },
    {
        "id":  "excel-s1-r14",
        "name":  "Tô Thị Thủy",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Biên chế",
        "qualification":  "Đại học - Cử nhân Quản trị kinh doanh",
        "contractTerm":  "HĐLV không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0978909899",
        "birthDate":  "1979-01-01",
        "start":  "",
        "salaryCoefficient":  "3.66",
        "salaryGrade":  "5/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "thôn Sơn Du- xã Phúc Thịnh-HN",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Viên chức phòng KHTH; Quê quán: thôn Sơn Du- xã Phúc Thịnh-HN; Đảng viên: Có; LLCT: Sơ cấp; Ngoại ngữ: Anh, x, Anh B; Tin học: CNTT theo thông tư 03/2014/TT-BTTTT, chuẩn Thông tư 03/2014/TT-BTTTT; Ngạch/CDNN: 01003"
    },
    {
        "id":  "excel-s1-r15",
        "name":  "Nguyễn Thị Minh Nguyệt",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Biên chế",
        "qualification":  "Đại học - Cử nhân kế toán",
        "contractTerm":  "HĐLV không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0945100206",
        "birthDate":  "1983-04-18",
        "start":  "",
        "salaryCoefficient":  "4.32",
        "salaryGrade":  "7/9",
        "salaryReviewDate":  "2027-01-01",
        "address":  "thôn Hải Bối, xã Vĩnh Thanh, TP HN",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Viên chức phòng KHTH; Quê quán: thôn Hải Bối, xã Vĩnh Thanh, TP HN"
    },
    {
        "id":  "excel-s1-r16",
        "name":  "Nguyễn Thị Thu Hương",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân kế toán",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0339835566",
        "birthDate":  "1991-10-18",
        "start":  "",
        "salaryCoefficient":  "3.00",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Xóm Chợ - Xã Đông Anh - TP Hà Nội",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Thôn Đại Đồng, xã Thiên Lộc, HN; Ngoại ngữ: Anh, B; Tin học: Chứng chỉ CNTT cơ bản"
    },
    {
        "id":  "excel-s1-r17",
        "name":  "Đặng Thị Thu Hà",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Quản trị kinh doanh",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0978146266",
        "birthDate":  "1979-06-12",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Gia Lương-Đông Anh-HN",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Gia Lương-Đông Anh-HN; Đảng viên: Có; Ngoại ngữ: Anh, Chứng chỉ trình độ B1, Anh B1; Tin học: CNTT theo thông tư 03/2014/TT-BTTTT, chuẩn Thông tư 03/2014/TT-BTTTT"
    },
    {
        "id":  "excel-s1-r18",
        "name":  "Phạm Hồng Ngọc",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Kế toán",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0976611991",
        "birthDate":  "1991-11-21",
        "start":  "",
        "salaryCoefficient":  "3.00",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Tổ 4 -Đông Anh-HN",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Khương Trung- Hà Nội; Đảng viên: Có; Ngoại ngữ: Anh; Tin học: CNTT theo thông tư 03/2014/TT-BTTTT, chuẩn Thông tư 03/2014/TT-BTTTT"
    },
    {
        "id":  "excel-s1-r19",
        "name":  "Lê Thị Hồng Linh",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư Quản lý đất đai",
        "contractTerm":  "Đến 31/03/2027",
        "contractSignedDate":  "",
        "phone":  "0936005113",
        "birthDate":  "1990-07-15",
        "start":  "",
        "salaryCoefficient":  "3.00",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "xã Vĩnh Thanh-HN",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: xã Đông Anh, Tp Hà Nội; Tin học: Chứng chỉ CNTT cơ bản"
    },
    {
        "id":  "excel-s1-r20",
        "name":  "Phạm Thị Ánh Nguyệt",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Trung cấp - Trung cấp Văn thư-lưu trữ",
        "contractTerm":  "Đến 31/03/2027",
        "contractSignedDate":  "",
        "phone":  "0982001048",
        "birthDate":  "1993-11-08",
        "start":  "",
        "salaryCoefficient":  "2.26",
        "salaryGrade":  "3/12",
        "salaryReviewDate":  "2027-07-01",
        "address":  "Tổ 21 -xã Thư Lâm-HN",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Hải Phòng; Ngoại ngữ: Anh, B, Anh B1; Tin học: Chứng chỉ CNTT cơ bản, chuẩn Thông tư 03/2014/TT-BTTTT"
    },
    {
        "id":  "excel-s1-r21",
        "name":  "Đặng Hương Giang",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Quản trị văn phòng",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "389806625",
        "birthDate":  "2002-06-25",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-09-01",
        "address":  "Tằng My-Phúc Thịnh- Hà Nội",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Lập Thạch - Phú Thọ; Tin học: Chứng chỉ CNTT cơ bản"
    },
    {
        "id":  "excel-s1-r22",
        "name":  "Đỗ Quyết Tiến",
        "gender":  "Nam",
        "departmentId":  "ke-hoach",
        "roleId":  "Pho-phong-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Kỹ sư kinh tế xây dựng",
        "contractTerm":  "Đến 31/03/2026",
        "contractSignedDate":  "",
        "phone":  "0919789985",
        "birthDate":  "1985-01-14",
        "start":  "",
        "salaryCoefficient":  "3.00",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Hà Lỗ-Thư Lâm-HN",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Hưng Yên"
    },
    {
        "id":  "excel-s1-r23",
        "name":  "Trần Thị Minh Yến",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Luật",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0354314784",
        "birthDate":  "2001-07-08",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-09-01",
        "address":  "Tổ 9 - Thư Lâm - Hà Nội",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Xã Tân An- Thành phố Hải Phòng; Tin học: Chứng chỉ CNTT cơ bản"
    },
    {
        "id":  "excel-s1-r24",
        "name":  "Lê Minh Nguyệt",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Cử nhân kế toán",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0965388169",
        "birthDate":  "2003-10-27",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-09-01",
        "address":  "Thôn Bầu, Thiên Lộc, Hà Nội",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Thôn Bầu, xã Thiên Lộc, thành phố Hà Nội"
    },
    {
        "id":  "excel-s1-r25",
        "name":  "Bùi Thị Quế Quyên",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Cử nhân kế toán",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0989450982",
        "birthDate":  "1982-09-10",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Trung Oai, Phúc Thịnh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Phường Trung Thành, TP Thái Nguyên"
    },
    {
        "id":  "excel-s1-r26",
        "name":  "Trương Thu Hiền",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư Công nghệ Kỹ thuật Môi trường",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0988922710",
        "birthDate":  "1992-11-15",
        "start":  "",
        "salaryCoefficient":  "3.00",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Thôn Nhì, Phúc Thịnh, Hà Nội",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng Dự án 1; Quê quán: Thôn Nhì, Phúc Thịnh, Hà Nội; Đảng viên: Có; LLCT: Sơ cấp"
    },
    {
        "id":  "excel-s1-r27",
        "name":  "Đinh Thị Thuỷ",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Cao đẳng - Cao đẳng Dược",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0965135990",
        "birthDate":  "1990-05-13",
        "start":  "",
        "salaryCoefficient":  "2.41",
        "salaryGrade":  "2/10",
        "salaryReviewDate":  "2028-10-01",
        "address":  "Đông Thuỷ-Sóc Sơn-HN",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Cổ Dương, Phúc Thịnh, HN"
    },
    {
        "id":  "excel-s1-r28",
        "name":  "Lê Xuân Hùng",
        "gender":  "Nam",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cao đẳng",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0968518971",
        "birthDate":  "1997-09-12",
        "start":  "",
        "salaryCoefficient":  "2.10",
        "salaryGrade":  "1/10",
        "salaryReviewDate":  "2028-10-01",
        "address":  "Hà Hương - Thư Lâm - Hà Nội",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Hà Hương - Thư Lâm - Hà Nội"
    },
    {
        "id":  "excel-s1-r29",
        "name":  "Đoàn Đức Tiên",
        "gender":  "Nam",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Cao đẳng - Cao đẳng Ngành kỹ thuật công trình",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0973979138",
        "birthDate":  "1984-01-03",
        "start":  "",
        "salaryCoefficient":  "3.03",
        "salaryGrade":  "4/10",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Do Hạ, Mê Linh, Phú Thọ",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng Dự án 1; Quê quán: Do Hạ, Mê Linh, Phú Thọ"
    },
    {
        "id":  "excel-s1-r30",
        "name":  "Phạm Quỳnh Dương",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân ngành kinh tế",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0983731509",
        "birthDate":  "2003-10-27",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "Xóm Dõng - Đông Anh - Hà Nội",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Xóm Dõng - Đông Anh - Hà Nội"
    },
    {
        "id":  "excel-s1-r31",
        "name":  "Hà Hải Linh",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân ngành Tài chính - Kế toán",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0379185051",
        "birthDate":  "2003-09-21",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "Tằng My - Phúc Thịnh - Hà Nội",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Tằng My - Phúc Thịnh - Hà Nội"
    },
    {
        "id":  "excel-s1-r32",
        "name":  "Phạm Thị Ngần",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kiến trúc sư quy hoạch vùng và đô thị",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0353584825",
        "birthDate":  "1993-02-23",
        "start":  "",
        "salaryCoefficient":  "3.00",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2028-08-01",
        "address":  "Thôn Tiền Phong, xã Thần Khê, tỉnh Hưng Yên",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Thôn Tiền Phong, xã Thần Khê, tỉnh Hưng Yên"
    },
    {
        "id":  "excel-s1-r33",
        "name":  "Lê Thị Nga",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân kế toán",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0963633216",
        "birthDate":  "1991-09-06",
        "start":  "",
        "salaryCoefficient":  "3.00",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2028-09-01",
        "address":  "Xóm Bến, xã Thiên Lộc, TP HN",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: xã Thiên Lộc, TP Hà Nội"
    },
    {
        "id":  "excel-s1-r34",
        "name":  "Nguyễn Trọng Chuyên",
        "gender":  "Nam",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư công nghệ kỹ thuật điện tử -viễn thông",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0965407081",
        "birthDate":  "2000-07-23",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-11-15",
        "address":  "Chung The Vesta, phường Phú Lãm, HN",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: thôn An Cường, xã Đồng Thịnh, tỉnh Ninh Bình"
    },
    {
        "id":  "excel-s1-r35",
        "name":  "Đào Xuân Hoà",
        "gender":  "Nam",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân xây dựng cầu đường",
        "contractTerm":  "Không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0926350050",
        "birthDate":  "1987-05-16",
        "start":  "",
        "salaryCoefficient":  "3.00",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "thôn Thường Lệ, xã Quang Minh, TP HN",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: thôn Thường Lệ, xã Quang Minh, TP HN"
    },
    {
        "id":  "excel-s1-r36",
        "name":  "Lê Hoàng Long",
        "gender":  "Nam",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Tài chính-Ngân hàng",
        "contractTerm":  "Đến 31/10/2028",
        "contractSignedDate":  "",
        "phone":  "0919238529",
        "birthDate":  "2001-03-15",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "",
        "address":  "thôn Tằng My, xã Phúc Thịnh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: thôn Tằng My, xã Phúc Thịnh, TP Hà Nội"
    },
    {
        "id":  "excel-s1-r37",
        "name":  "Ngô Trúc Anh",
        "gender":  "Nữ",
        "departmentId":  "ke-hoach",
        "roleId":  "chuyen-vien-ke-hoach",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Quản trị nhân lực",
        "contractTerm":  "",
        "contractSignedDate":  "",
        "phone":  "0868658481",
        "birthDate":  "2002-08-07",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "",
        "address":  "Thôn Lương Quy, xã Thư Lâm, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng KHTH; Chức vụ gốc: Nhân viên phòng KHTH; Quê quán: Thôn Lương Quy, xã Thư Lâm, TP Hà Nội"
    },
    {
        "id":  "excel-s2-r11",
        "name":  "Dương Văn Hải",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "truong-phong-du-an",
        "contract":  "Biên chế",
        "qualification":  "Đại học - Kỹ sư quản lý xây dựng",
        "contractTerm":  "Đến 10/10/2029",
        "contractSignedDate":  "",
        "phone":  "0964012033",
        "birthDate":  "1990-10-10",
        "start":  "",
        "salaryCoefficient":  "3.00",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2028-08-01",
        "address":  "Hà Phong-Thư Lâm-HN",
        "note":  "Nguồn Excel: Phòng DA1; Chức vụ gốc: Trưởng phòng Dự án 1; Quê quán: Hà Phong-Thư Lâm-HN; Đảng viên: Có; Ngoại ngữ: Anh, Chứng chỉ trình độ B; Tin học: Chứng chỉ trình độ B, chuẩn Thông tư 03/2014/TT-BTTTT; Ngạch/CDNN: Kỹ sư hạng III, V.05.02.07"
    },
    {
        "id":  "excel-s2-r12",
        "name":  "Lưu Đức Lân",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "truong-phong-du-an",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư XD cầu đường",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0982164936",
        "birthDate":  "1986-03-20",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Bắc Đông Hạ, Cổ Lễ, Ninh Bình",
        "note":  "Nguồn Excel: Phòng DA1; Chức vụ gốc: Phó Trưởng phòng Dự án 1; Quê quán: Bắc Đông Hạ, Cổ Lễ, Ninh Bình"
    },
    {
        "id":  "excel-s2-r13",
        "name":  "Tạ Hồng Thi",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư XD đường bộ",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0915505123",
        "birthDate":  "1982-02-12",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Phường Định Công - Hà Nội",
        "note":  "Nguồn Excel: Phòng DA1; Chức vụ gốc: Nhân viên phòng Dự án 1; Quê quán: Xã Kim Anh, Hà Nội; Ngoại ngữ: Tiếng Anh"
    },
    {
        "id":  "excel-s2-r14",
        "name":  "Nguyễn Văn Hà",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư Kinh tế thuỷ lợi",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0972122177",
        "birthDate":  "1979-12-02",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2027-11-01",
        "address":  "Xóm Bàng, xã Thiên Lộc, TP. Hà Nội",
        "note":  "Nguồn Excel: Phòng DA1; Chức vụ gốc: Nhân viên phòng Dự án 1; Quê quán: Xóm Bàng, xã Thiên Lộc, TP. Hà Nội; Ngoại ngữ: Tiếng Anh, B"
    },
    {
        "id":  "excel-s2-r15",
        "name":  "Hồ Sỹ Sơn",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Thạc sĩ - ThS quản trị kinh doanh - Kỹ sư Cầu - đường",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0987666300",
        "birthDate":  "1986-09-04",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2026-09-01",
        "address":  "phường Hoàng Mai, thành phố Hà Nội",
        "note":  "Nguồn Excel: Phòng DA1; Chức vụ gốc: Nhân viên phòng Dự án 1; Quê quán: xã Quỳnh Phú, Nghệ An; Ngoại ngữ: Tiếng Anh, B; Tin học: B"
    },
    {
        "id":  "excel-s2-r16",
        "name":  "Hoàng Hữu Hùng",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư XD cầu hầm",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0913872368",
        "birthDate":  "1979-09-24",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Khu 4, xã Bản Nguyên, Phú Thọ",
        "note":  "Nguồn Excel: Phòng DA1; Chức vụ gốc: Nhân viên phòng Dự án 1; Quê quán: Khu 4, xã Bản Nguyên, Phú Thọ"
    },
    {
        "id":  "excel-s2-r17",
        "name":  "Hà Thế Hoàn",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "Pho-phong-du-an",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư công nghệ kỹ thuật giao thông",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0983663918",
        "birthDate":  "1993-11-27",
        "start":  "",
        "salaryCoefficient":  "3.00",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Tổ 4, xã Đông Anh-Hà Nội",
        "note":  "Nguồn Excel: Phòng DA1; Chức vụ gốc: Nhân viên phòng Dự án 1; Quê quán: Hà Nội; Đảng viên: Có"
    },
    {
        "id":  "excel-s2-r18",
        "name":  "Phạm Tràng Quang",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư kỹ thuật công trình xây dựng",
        "contractTerm":  "Đến 31/05/2027",
        "contractSignedDate":  "",
        "phone":  "0966028297",
        "birthDate":  "1997-02-28",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Biểu Khê-Thư Lâm-HN",
        "note":  "Nguồn Excel: Phòng DA1; Chức vụ gốc: Nhân viên phòng Dự án 1; Quê quán: Biểu Khê, Xã Thư Lâm, TP Hà Nội"
    },
    {
        "id":  "excel-s2-r19",
        "name":  "Lê Nam Thắng",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư Công trình Thủy lợi, Kỹ sư Công trình Cầu đường bộ",
        "contractTerm":  "Đến 31/01/2027",
        "contractSignedDate":  "",
        "phone":  "0986461980",
        "birthDate":  "1978-11-08",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2027-02-01",
        "address":  "Tổ 12, xã Thư Lâm-HN",
        "note":  "Nguồn Excel: Phòng DA1; Chức vụ gốc: Nhân viên phòng Dự án 1; Quê quán: Xã Tiền Phong, huyện Mê Linh, Hà Nội; Đảng viên: Có; Ngoại ngữ: Tiếng Anh"
    },
    {
        "id":  "excel-s2-r20",
        "name":  "Nguyễn Thành Trung",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Thạc sĩ, Đại học - Thạc sĩ kỹ thuật xây dựng công trình giao thông; Kỹ sư xây dựng ngành cơ sở hạ tầng giao thông",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0989873484",
        "birthDate":  "1988-10-26",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Lộc Hà, xã Đông Anh, Tp Hà Nội",
        "note":  "Nguồn Excel: Phòng DA1; Chức vụ gốc: Nhân viên phòng Dự án 1; Quê quán: xã Đông Anh, Tp Hà Nội"
    },
    {
        "id":  "excel-s2-r21",
        "name":  "Trịnh Văn Đông",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư kỹ thuật công trình xây dựng",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0989808300",
        "birthDate":  "1995-04-12",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-11-15",
        "address":  "Thôn Hà Lỗ - Thư Lâm - Hà Nội",
        "note":  "Nguồn Excel: Phòng DA1; Chức vụ gốc: Nhân viên phòng Dự án 1; Quê quán: Thôn Hà Lỗ - Thư Lâm - Hà Nội"
    },
    {
        "id":  "excel-s2-r22",
        "name":  "Trương Duy Sơn",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư công trình thuỷ lợi",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0983823690",
        "birthDate":  "1984-10-30",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2029-01-01",
        "address":  "Tổ 24 xã Phúc Thịnh, HN",
        "note":  "Nguồn Excel: Phòng DA1; Chức vụ gốc: Nhân viên phòng Dự án 1; Quê quán: xã Tân Kỳ- TP Hải Phòng"
    },
    {
        "id":  "excel-s2-r23",
        "name":  "Nguyễn Hoàng Sâm",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư xây dựng cầu đường bộ",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0934568204",
        "birthDate":  "1986-06-06",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2029-03-05",
        "address":  "Số 9, ngõ 1104 đường La Thành, phường Giảng Võ, thành phố Hà Nội",
        "note":  "Nguồn Excel: Phòng DA1; Chức vụ gốc: Nhân viên Phòng Dự án 1; Quê quán: Phường ái quốc, thành phố Hải Phòng"
    },
    {
        "id":  "excel-s3-r11",
        "name":  "Trịnh Xuân Điềm",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "truong-phong-du-an",
        "contract":  "Biên chế",
        "qualification":  "Đại học - Kỹ sư kinh tế xây dựng",
        "contractTerm":  "HĐLV không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0983661692",
        "birthDate":  "1978-07-20",
        "start":  "",
        "salaryCoefficient":  "3.99",
        "salaryGrade":  "6/9",
        "salaryReviewDate":  "2027-07-01",
        "address":  "Tiên Kha, Phúc Thịnh, Hà Nội",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Trưởng phòng Dự án 2; Quê quán: Thôn Hà Phong, xã Thư Lâm-TP HN; Đảng viên: Có; LLCT: Trung cấp; Tin học: chuẩn Thông tư 03/2014/TT-BTTTT; Ngạch/CDNN: V.05.02.07"
    },
    {
        "id":  "excel-s3-r12",
        "name":  "Lê Hồng Thoan",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "Pho-phong-du-an",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Thạc sĩ - ThS Kỹ thuật XD công trình đặc biệt -Kỹ sư XD DD\u0026CN",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0973593372",
        "birthDate":  "1990-08-12",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Thôn Nhuế - Thiên Lộc - Hà Nội",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Phó trưởng phòng Dự án 2; Quê quán: Thôn Nhuế - Thiên Lộc - Hà Nội; Đảng viên: Có"
    },
    {
        "id":  "excel-s3-r13",
        "name":  "Nguyễn Văn Trường",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Biên chế",
        "qualification":  "Đại học - Cử nhân Công nghệ kỹ thuật công trình xây dựng",
        "contractTerm":  "Đến 03/01/2030",
        "contractSignedDate":  "",
        "phone":  "0966593836",
        "birthDate":  "1992-08-03",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-03-03",
        "address":  "Hà Lâm 3-Thư Lâm-HN",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Viên chức phòng Dự án 2; Quê quán: Hà Lâm 3-Thư Lâm-HN; Ngoại ngữ: Anh, B2, Anh A2; Tin học: Chứng chỉ ứng dụng thông tin cơ bản, chuẩn Thông tư 03/2014/TT-BTTTT; Ngạch/CDNN: Kỹ sư hạng III, V.05.02.07"
    },
    {
        "id":  "excel-s3-r14",
        "name":  "Trịnh Đức Thọ",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Biên chế",
        "qualification":  "Đại học - Kỹ sư Xây dựng cầu - đường bộ",
        "contractTerm":  "Đến 03/01/2030",
        "contractSignedDate":  "",
        "phone":  "0946951982",
        "birthDate":  "1982-05-09",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-04-01",
        "address":  "Hà Hương-Thư Lâm-HN",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Viên chức phòng Dự án 2; Quê quán: Phường Đông Hoa Lư-Ninh Bình; Đảng viên: Có; Ngoại ngữ: Anh, Chứng chỉ trình độ B1, Anh B1; Tin học: Chứng chỉ ứng dụng thông tin cơ bản, chuẩn Thông tư 03/2014/TT-BTTTT; Ngạch/CDNN: Kỹ sư hạng III, V.05.02.07"
    },
    {
        "id":  "excel-s3-r15",
        "name":  "Vũ Thị Huệ",
        "gender":  "Nữ",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư Kinh tế xây dựng",
        "contractTerm":  "Đến 30/04/2026",
        "contractSignedDate":  "",
        "phone":  "0982344497",
        "birthDate":  "1997-12-16",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "xã Tương Lạc,Tỉnh Thanh Hoá",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Nhân viên phòng Dự án 2; Quê quán: xã Tương Lạc,Tỉnh Thanh Hoá"
    },
    {
        "id":  "excel-s3-r16",
        "name":  "Hoàng Tiến Dũng",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Thạc sĩ - ThS QLDA XD - Kỹ sư XDDD và CN",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0986814085",
        "birthDate":  "1997-12-01",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "tổ 11, xã Thư Lâm, thành phố Hà Nội",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Nhân viên phòng Dự án 2; Quê quán: xã Xuân Hải, huyện Nghi Xuân, tỉnh Hà Tĩnh; Đảng viên: Có; LLCT: Sơ cấp"
    },
    {
        "id":  "excel-s3-r17",
        "name":  "Đặng Trần Hồng Hải",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Kỹ sư kinh tế XD",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0989559866",
        "birthDate":  "1974-12-22",
        "start":  "",
        "salaryCoefficient":  "3.66",
        "salaryGrade":  "5/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "Yên Viên - xã Phù Đổng- HN",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Nhân viên phòng Dự án 2"
    },
    {
        "id":  "excel-s3-r18",
        "name":  "Bùi Tuấn Anh",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Thạc sĩ - ThS kỹ thuật XD công trình đặc biệt - Kỹ sư kỹ thuật XD",
        "contractTerm":  "HĐLĐ không XĐ thời hạn",
        "contractSignedDate":  "",
        "phone":  "0372599012",
        "birthDate":  "1990-08-01",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Xã Phùng Nguyên, tỉnh Phú Thọ",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Nhân viên phòng Dự án 2; Quê quán: Xã Phùng Nguyên, tỉnh Phú Thọ; Đảng viên: Có"
    },
    {
        "id":  "excel-s3-r19",
        "name":  "Tống Thị Thuý Hà",
        "gender":  "Nữ",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư XD DD\u0026CN",
        "contractTerm":  "Đến 31/05/2026",
        "contractSignedDate":  "",
        "phone":  "0984689845",
        "birthDate":  "1991-06-20",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-06-01",
        "address":  "Khu đô thị mới Dương Nội, Phường Hà Đông, thành phố Hà Nội",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Nhân viên phòng Dự án 2; Quê quán: Phường Bỉm Sơn, Tỉnh Thanh Hoá; Đảng viên: Có"
    },
    {
        "id":  "excel-s3-r20",
        "name":  "Nguyễn Ngọc Ánh",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư Ngành Kỹ thuật xây dựng",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0338969342",
        "birthDate":  "1991-03-10",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "TDP Cáo Đỉnh 3 - Xuân Đỉnh - Hà Nội",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Nhân viên phòng Dự án 2; Quê quán: TDP Cáo Đỉnh 3 - Xuân Đỉnh - Hà Nội"
    },
    {
        "id":  "excel-s3-r21",
        "name":  "Phạm Văn Hoằng",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư Ngành Xây dựng Dân dụng và Công nghiệp",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0983356279",
        "birthDate":  "1983-07-26",
        "start":  "",
        "salaryCoefficient":  "3.00",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "P816 - Linh Đàm - Hoàng Liệt - Hà Nội",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Nhân viên phòng Dự án 2; Quê quán: Xuân Châu - Xuân Dương - Nam Định"
    },
    {
        "id":  "excel-s3-r22",
        "name":  "Nguyễn Hoàng Nam",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân kế toán",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0345303665",
        "birthDate":  "2001-07-11",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-11-01",
        "address":  "thôn Hải Bối, xã Vĩnh Thanh, TP HN",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Nhân viên phòng Dự án 2; Quê quán: thôn Hải Bối, xã Vĩnh Thanh, TP HN"
    },
    {
        "id":  "excel-s3-r23",
        "name":  "Phan Tiến Dũng",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kiến trúc sư kiến trúc",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0963781856",
        "birthDate":  "2001-02-18",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-11-15",
        "address":  "số nhà C3-07, tổ dân cư thuỷ lợi 2, xã Sóc Sơn, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Nhân viên phòng Dự án 2; Quê quán: Thái Bình"
    },
    {
        "id":  "excel-s3-r24",
        "name":  "Nguyễn Ngọc Chung",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân công trình Thuỷ Lợi",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0912768380",
        "birthDate":  "1980-05-14",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2028-11-15",
        "address":  "Thôn Phương Trạch, xã Vĩnh Thanh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Nhân viên phòng Dự án 2; Quê quán: Thôn Phương Trạch, xã Vĩnh Thanh, TP Hà Nội"
    },
    {
        "id":  "excel-s3-r25",
        "name":  "Ngô Việt Linh",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư kỹ thuật công trình xây dựng",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0977583296",
        "birthDate":  "1996-10-04",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2029-03-05",
        "address":  "Khu chợ Kim, xã Thư Lâm, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Nhân viên Phòng Dự án 2; Quê quán: Khu chợ Kim, xã Thư Lâm, TP Hà Nội"
    },
    {
        "id":  "excel-s3-r26",
        "name":  "Vũ Văn Giáp",
        "gender":  "Nam",
        "departmentId":  "du-an",
        "roleId":  "ky-su-giam-sat",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư xây dựng",
        "contractTerm":  "Thử việc 60 ngày (từ ngày 02/3/2026 -29/4/2026)",
        "contractSignedDate":  "",
        "phone":  "0972701140",
        "birthDate":  "1987-07-06",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "",
        "address":  "Khu Bồ Sơn, phường Võ Cường, tỉnh Bắc Ninh",
        "note":  "Nguồn Excel: Phòng DA2; Chức vụ gốc: Nhân viên phòng Dự án 2; Quê quán: Thôn Thiên Đức, xã Trung chính, tỉnh Bắc Ninh"
    },
    {
        "id":  "excel-s4-r11",
        "name":  "Dương Xuân Thu",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "truong-phong-gpmb",
        "contract":  "Biên chế",
        "qualification":  "Đại học - Kỹ sư Quản lý đất đai",
        "contractTerm":  "HĐLV không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0983802409",
        "birthDate":  "1978-12-13",
        "start":  "",
        "salaryCoefficient":  "4.65",
        "salaryGrade":  "8/9",
        "salaryReviewDate":  "2028-08-01",
        "address":  "Hà Lỗ-Thư Lâm-HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Trưởng phòng GPMB; Quê quán: Hà Lỗ-Thư Lâm-HN; Đảng viên: Có; LLCT: Trung cấp; Ngoại ngữ: Anh, Chứng chỉ C, Anh B; Tin học: Chứng chỉ, chuẩn Thông tư 03/2014/TT-BTTTT; Ngạch/CDNN: Kỹ sư hạng III, V.05.02.07"
    },
    {
        "id":  "excel-s4-r12",
        "name":  "Vũ Thị Hằng Nga",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Biên chế",
        "qualification":  "Đại học - Quản trị kinh doanh",
        "contractTerm":  "HĐLV không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0987642816",
        "birthDate":  "1990-02-10",
        "start":  "",
        "salaryCoefficient":  "3.66",
        "salaryGrade":  "5/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Xuân Nộn-Thư Lâm-HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Viên chức phòng GPMB; Quê quán: Cổ Bi- Gia Lâm- Hà Nội; Đảng viên: Có; LLCT: Sơ cấp; Ngoại ngữ: Anh, Chứng chỉ C, Anh C; Tin học: CNTT theo thông tư 03/2014/TT-BTTTT, chuẩn Thông tư 03/2014/TT-BTTTT; Ngạch/CDNN: 01003"
    },
    {
        "id":  "excel-s4-r13",
        "name":  "Hà Văn Thịnh",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư quản lý đất đai; Kỹ sư công nghệ kỹ thuật giao thông",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0916103659",
        "birthDate":  "1991-01-20",
        "start":  "",
        "salaryCoefficient":  "3",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Đại Đồng, Thiên Lộc, Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Đại Đồng, Thiên Lộc, Hà Nội; Đảng viên: Có"
    },
    {
        "id":  "excel-s4-r14",
        "name":  "Ngô Thùy Linh",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhận Quản lý tài nguyên và môi trường",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0931157040",
        "birthDate":  "2002-09-13",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-02-01",
        "address":  "Thôn Vệ-xã Phúc Thịnh-HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Thôn Vệ-xã Phúc Thịnh-HN; Ngoại ngữ: Tiếng Anh, B; Tin học: MOS, Chứng chỉ CNTT cơ bản"
    },
    {
        "id":  "excel-s4-r15",
        "name":  "Tô Quang Kiên",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "pho-phong-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân khoa học cây trồng",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0988329518",
        "birthDate":  "1993-07-23",
        "start":  "",
        "salaryCoefficient":  "3",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Sơn Du, Xã Phúc Thịnh - TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Sơn Du - Phúc Thịnh, HN"
    },
    {
        "id":  "excel-s4-r16",
        "name":  "Phạm Phúc Ánh",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Thạc sĩ - Cử nhân Quản lý dất đai, Thạc sỹ Quản lý đất đai",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0967293556",
        "birthDate":  "1991-08-17",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Thôn Đìa- Phúc Thịnh-HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Thôn Đìa- Phúc Thịnh-HN; Đảng viên: Có; Ngoại ngữ: Tiếng Anh, B; Tin học: Chứng chỉ CNTT cơ bản"
    },
    {
        "id":  "excel-s4-r17",
        "name":  "Tô Văn Hào",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Luật",
        "contractTerm":  "Đến 28/02/2027",
        "contractSignedDate":  "",
        "phone":  "\u00270855405132",
        "birthDate":  "1999-02-12",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Sơn Du, Xã Phúc Thịnh- TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Sơn Du, Xã Phúc Thịnh- TP Hà Nội"
    },
    {
        "id":  "excel-s4-r18",
        "name":  "Nguyễn Thị Thành Thương",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân quản lý đất đai",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0869166976",
        "birthDate":  "2001-08-08",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-02-01",
        "address":  "Lương Nỗ-Phúc Thịnh-HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Lương Nỗ-Phúc Thịnh-HN"
    },
    {
        "id":  "excel-s4-r19",
        "name":  "Nguyễn Hữu Hợp",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân kinh tế",
        "contractTerm":  "Đến 31/05/2027",
        "contractSignedDate":  "",
        "phone":  "\u00270397799816",
        "birthDate":  "2000-12-18",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2027-06-01",
        "address":  "Lương Nỗ-Phúc Thịnh-HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Lương Nỗ-Phúc Thịnh-HN; Tin học: Chứng chỉ CNTT cơ bản"
    },
    {
        "id":  "excel-s4-r20",
        "name":  "Phạm Long Vũ",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư kinh tế vận tải",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0936794567",
        "birthDate":  "1998-08-12",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2027-11-01",
        "address":  "Thôn Đìa-Phúc Thịnh-HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Thôn Đìa-Phúc Thịnh-HN; Ngoại ngữ: Tiếng Anh, Chứng chỉ"
    },
    {
        "id":  "excel-s4-r21",
        "name":  "Nguyễn Quốc Huy",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân quản lý đất đai",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0862018014",
        "birthDate":  "2002-06-14",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2027-11-01",
        "address":  "Lễ Pháp-Phúc Thịnh-HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Lễ Pháp-Phúc Thịnh-HN; Tin học: CNTT cơ bản"
    },
    {
        "id":  "excel-s4-r22",
        "name":  "Nguyễn Thị Minh Hương",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư Quản lý dất đai, cử nhân kế toán",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0901721731",
        "birthDate":  "1991-09-08",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-09-01",
        "address":  "thôn Đồng - Phúc Thịnh - HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Đông Anh - Hà Nội; Đảng viên: Có"
    },
    {
        "id":  "excel-s4-r23",
        "name":  "Nguyễn Thu Trang",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Quản lý đất đai",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0941062164",
        "birthDate":  "1998-08-25",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-09-01",
        "address":  "Lã Côi, Phù Đổng, Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Xã Phù Đổng, Hà Nội; Ngoại ngữ: Tiếng Anh; Tin học: CNTT cơ bản"
    },
    {
        "id":  "excel-s4-r24",
        "name":  "Vũ Thanh Thanh Hiền",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân quản lý tài nguyên và môi trường",
        "contractTerm":  "Đến 28/02/2027",
        "contractSignedDate":  "",
        "phone":  "0347944436",
        "birthDate":  "1995-12-20",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Tổ 4 , xã Đông Anh-HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Ngọc Vừng, đặc khu Vân Đồn-Quảng Ninh; Đảng viên: Có; Ngoại ngữ: Tiếng Anh, Chứng chỉ, Anh A2; Tin học: Chứng chỉ tin học IC3, tin học IC3"
    },
    {
        "id":  "excel-s4-r25",
        "name":  "Dương Thị Huyền Trang",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Cao đẳng - Cao đẳng sư phạm",
        "contractTerm":  "Đến 30/09/2026",
        "contractSignedDate":  "",
        "phone":  "0973719658",
        "birthDate":  "1990-10-27",
        "start":  "",
        "salaryCoefficient":  "2.41",
        "salaryGrade":  "2/10",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Cổ Dương, Phúc Thịnh-HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Hà Lỗ, Xã Thư Lâm, tp Hà Nội"
    },
    {
        "id":  "excel-s4-r26",
        "name":  "Đặng Thị Thơm",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư QLĐĐ",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "\u00270335868701",
        "birthDate":  "1997-07-11",
        "start":  "",
        "salaryCoefficient":  "3",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Lực Canh, Đông Anh, HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Đông Anh, HN; Ngoại ngữ: Tiếng Anh, Văn bằng"
    },
    {
        "id":  "excel-s4-r27",
        "name":  "Trịnh Thái Sơn",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân thực hành ngành Luật, kinh tế, quản lý",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0379676998",
        "birthDate":  "1996-12-01",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-03-01",
        "address":  "Tổ 7, Xã Đông Anh, tp Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Xã Thư Lâm, tp Hà Nội; Đảng viên: Có; Ngoại ngữ: Tiếng Anh, Chứng chỉ, Anh TOEIC; Tin học: Chứng chỉ CNTT cơ bản"
    },
    {
        "id":  "excel-s4-r28",
        "name":  "Nguyễn Thanh Hiếu",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân kế toán",
        "contractTerm":  "Đến 31/03/2026",
        "contractSignedDate":  "",
        "phone":  "0966012339",
        "birthDate":  "1993-12-06",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Thôn Ninh Nội-Tân Dân-Sóc Sơn-HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Thái Nguyên,Thái Thuỵ, Thái Bình"
    },
    {
        "id":  "excel-s4-r29",
        "name":  "Ngô Quang Vinh",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Tài chính-Ngân hàng",
        "contractTerm":  "Đến 31/03/2026",
        "contractSignedDate":  "",
        "phone":  "0963807051",
        "birthDate":  "1999-08-14",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-04-15",
        "address":  "Sơn Du, Phúc Thịnh, HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Sơn Du, Phúc Thịnh, HN"
    },
    {
        "id":  "excel-s4-r30",
        "name":  "Hoàng Đức Ngọc",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư Ngành Quản lý đất đai",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0355995389",
        "birthDate":  "1993-09-20",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "Thôn Hà Lỗ - Thư Lâm - Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Thôn Hà Lỗ - Thư Lâm - Hà Nội"
    },
    {
        "id":  "excel-s4-r31",
        "name":  "Lê Trọng Hậu",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Ngành Quản lý đất đai",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0966753597",
        "birthDate":  "2003-05-27",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "Lễ Pháp - Phúc Thịnh - Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Lễ Pháp - Phúc Thịnh - Hà Nội"
    },
    {
        "id":  "excel-s4-r32",
        "name":  "Nguyễn Đăng Quang Trung",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Ngành Khoa học môi trường",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0389311196",
        "birthDate":  "1996-10-22",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "Trung Oai - Phúc Thịnh - Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Trung Oai - Phúc Thịnh - Hà Nội"
    },
    {
        "id":  "excel-s4-r33",
        "name":  "Phạm Thị Thuỳ Trang",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Ngành Tài chính ngân hàng",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0345284205",
        "birthDate":  "2000-11-01",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "Hà Hương - Thư Lâm - Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Hà Hương - Thư Lâm - Hà Nội"
    },
    {
        "id":  "excel-s4-r34",
        "name":  "Trần Quang Quý",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Kế toán",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0972528229",
        "birthDate":  "1988-08-15",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "Đản Mỗ, Đông Anh, HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Đa Lộc, Ân Thi, Hưng Yên"
    },
    {
        "id":  "excel-s4-r35",
        "name":  "Dương Tuấn Đạt",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân kinh tế",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0343852779",
        "birthDate":  "1999-02-01",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "Hà Hương - Thư Lâm - Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Hà Hương - Thư Lâm - Hà Nội"
    },
    {
        "id":  "excel-s4-r36",
        "name":  "Vũ Thanh Thảo",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Luật",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0901409666",
        "birthDate":  "2003-12-12",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "Tập thể cơ khí và xây dựng Thăng Long, xã Vĩnh Thanh, Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: xã Nghĩa Đồng, tỉnh Nam Định"
    },
    {
        "id":  "excel-s4-r37",
        "name":  "Đinh Thị Uyên",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư quản lý dất đai",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0966052722",
        "birthDate":  "1994-06-03",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "thôn Ngọc Giang, xã Vĩnh Thanh, TP HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: thôn Ngọc Giang, xã Vĩnh Thanh, TP HN"
    },
    {
        "id":  "excel-s4-r38",
        "name":  "Nguyễn Văn Vấn",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Kế toán",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0985565188",
        "birthDate":  "1988-01-18",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2028-08-01",
        "address":  "Biểu Khê, Thư Lâm, HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Biểu Khê, Thư Lâm, HN"
    },
    {
        "id":  "excel-s4-r39",
        "name":  "Nguyễn Mạnh Hiệp",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Luật",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0982336682",
        "birthDate":  "1998-12-02",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "thôn Sơn Du, xã Phúc Thịnh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: thôn Sơn Du, xã Phúc Thịnh, TP Hà Nội"
    },
    {
        "id":  "excel-s4-r40",
        "name":  "Nguyễn Thị Vân Anh",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Tài chính-ngân hàng",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0989661294",
        "birthDate":  "1994-12-06",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-11-01",
        "address":  "thôn Sơn Du, xã Phúc Thịnh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: thôn Cán Khê, xã Phúc Thịnh, TP Hà Nội"
    },
    {
        "id":  "excel-s4-r41",
        "name":  "Triệu Thành An",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Luật",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0973909761",
        "birthDate":  "2003-08-22",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-11-15",
        "address":  "Đội 7, Khê Nữ-Phúc Thịnh-HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Khê Nữ-Phúc Thịnh-HN"
    },
    {
        "id":  "excel-s4-r42",
        "name":  "Đinh Quang Minh",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân hệ thống thông tin quản lý",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0366939456",
        "birthDate":  "1995-10-17",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-11-15",
        "address":  "Số 25/15 ngõ Gốc Đề, đường Minh Khai, phường Tương Mai, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: xã Vũ Dương, tỉnh Ninh Bình"
    },
    {
        "id":  "excel-s4-r43",
        "name":  "Nguyễn Ngọc Huyền",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Quản trị kinh doanh",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0969844176",
        "birthDate":  "2000-12-16",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-11-15",
        "address":  "Thôn Phúc Hậu, xã Đông Anh, Hn",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Thôn Phúc Hậu, xã Đông Anh, Hn"
    },
    {
        "id":  "excel-s4-r44",
        "name":  "Bạch Vũ Khánh Linh",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Thạc sĩ kinh doanh thương mại",
        "contractTerm":  "Không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0963916162",
        "birthDate":  "1999-05-20",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2028-12-01",
        "address":  "Số nhà 8, ngõ 3, đường 18M, Phường Hà Đông, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Phường Hà Đông, TP Hà Nội"
    },
    {
        "id":  "excel-s4-r45",
        "name":  "Nguyễn Thị Minh Hoài",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Kế toán",
        "contractTerm":  "Không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0385924189",
        "birthDate":  "2002-05-11",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "2028-12-01",
        "address":  "thôn Trung Oai, xã Phúc Thịnh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: thôn Trung Oai, xã Phúc Thịnh, TP Hà Nội"
    },
    {
        "id":  "excel-s4-r46",
        "name":  "Trần Văn Độ",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Cao đẳng - Cao đăng công nghệ thông tin (Phát triển phần mềm)",
        "contractTerm":  "Không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0963418988",
        "birthDate":  "1988-08-26",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "2028-12-01",
        "address":  "thôn Hải Bối, Vĩnh Thanh, Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: thôn Hải Bối, Vĩnh Thanh, Hà Nội"
    },
    {
        "id":  "excel-s4-r47",
        "name":  "Nguyễn Thị Thảo",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Tài chính-Ngân hàng",
        "contractTerm":  "Không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0866913202",
        "birthDate":  "2002-12-11",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "2028-12-01",
        "address":  "Thôn Cầu Cả, Đông Anh, HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Thôn Cầu Cả, Đông Anh, HN"
    },
    {
        "id":  "excel-s4-r48",
        "name":  "Tô Việt Hiệp",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Cao đẳng - Cử nhân chăn nuôi",
        "contractTerm":  "Không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0981269262",
        "birthDate":  "2000-08-05",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "2028-12-01",
        "address":  "Sơn Du-Phúc Thịnh, Hn",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Sơn Du-Phúc Thịnh, Hn"
    },
    {
        "id":  "excel-s4-r49",
        "name":  "Nguyễn Cẩm Trang",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Quản trị khách sạn",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0768110500",
        "birthDate":  "2000-05-11",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2029-01-01",
        "address":  "xóm Đông, thôn Khê Nữ, xã Phúc Thịnh, TP HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: xóm Đông, thôn Khê Nữ, xã Phúc Thịnh, TP HN"
    },
    {
        "id":  "excel-s4-r50",
        "name":  "Đỗ Ngọc Dương",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Thạc sĩ - Thạc sĩ quản lý kinh tế; cử nhân Luật kinh tế",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0983386832",
        "birthDate":  "1989-06-20",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2029-01-01",
        "address":  "số nhà 02, ngõ 14 thôn Bến Trung- xã Phúc Thịnh, TP HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: xã Phúc Thịnh-TP HN"
    },
    {
        "id":  "excel-s4-r51",
        "name":  "Lê Đức Tâm",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Luật",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0976060839",
        "birthDate":  "1995-08-07",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2029-01-01",
        "address":  "Khu Cầu lớn, xã Phúc Thịnh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Khu Cầu lớn, xã Phúc Thịnh, TP Hà Nội"
    },
    {
        "id":  "excel-s4-r52",
        "name":  "Lương Mai Chi",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Luật",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0963845443",
        "birthDate":  "2002-09-22",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2029-03-05",
        "address":  "thôn Lại Đà, xã Đông Anh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: thôn Lại Đà, xã Đông Anh, TP Hà Nội"
    },
    {
        "id":  "excel-s4-r53",
        "name":  "Đinh Thị Thúy Hạnh",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Luật",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0343523185",
        "birthDate":  "2001-10-16",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2029-03-05",
        "address":  "thôn Cổ Dương, xã Phúc Thịnh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: thôn Cổ Dương, xã Phúc Thịnh, TP Hà Nội"
    },
    {
        "id":  "excel-s4-r54",
        "name":  "Đinh Thị Huyền Trang",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Luật",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0394682708",
        "birthDate":  "2003-06-25",
        "start":  "",
        "salaryCoefficient":  "2.34",
        "salaryGrade":  "1/9",
        "salaryReviewDate":  "2029-03-05",
        "address":  "thôn Cổ Dương, xã Phúc Thịnh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: thôn Cổ Dương, xã Phúc Thịnh, TP Hà Nội"
    },
    {
        "id":  "excel-s4-r55",
        "name":  "Nguyễn Tú Anh",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Quản trị nhân lực",
        "contractTerm":  "Thử việc 60 ngày (từ ngày 02/3/2026 -29/4/2026)",
        "contractSignedDate":  "",
        "phone":  "0346893888",
        "birthDate":  "2002-04-16",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "",
        "address":  "Tổ 3, xã Đông Anh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: xã Kim Liên, tỉnh Nghệ An"
    },
    {
        "id":  "excel-s4-r56",
        "name":  "Nguyễn Thành Long",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Cao đẳng - Kỹ sư thực hành Tin học ứng dụng",
        "contractTerm":  "Thử việc 60 ngày (từ ngày 02/02/2026 -31/3/2026)",
        "contractSignedDate":  "",
        "phone":  "0346893888",
        "birthDate":  "2003-04-05",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "",
        "address":  "thôn Lã Côi, xã Phù Đổng, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Ninh Hiệp, xã Phù Đổng, TP Hà Nội"
    },
    {
        "id":  "excel-s4-r57",
        "name":  "Nguyễn Văn Sơn",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Cao đẳng - Kỹ sư kỹ thuật mỏ",
        "contractTerm":  "Thử việc 60 ngày (từ ngày 02/02/2026 -31/3/2026)",
        "contractSignedDate":  "",
        "phone":  "0369433819",
        "birthDate":  "1996-07-12",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "",
        "address":  "thôn Thù Lỗ, xã Thư Lâm, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: thôn Thù Lỗ, xã Thư Lâm, TP Hà Nội"
    },
    {
        "id":  "excel-s4-r58",
        "name":  "Nguyễn Văn Đức",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Cao đẳng - Cử nhân khoa học Kinh tế và tài chính",
        "contractTerm":  "Thử việc 60 ngày (từ ngày 02/02/2026 -31/3/2026)",
        "contractSignedDate":  "",
        "phone":  "0945621313",
        "birthDate":  "2000-10-07",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "",
        "address":  "thôn Thù Lỗ, xã Thư Lâm, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: thôn Thù Lỗ, xã Thư Lâm, TP Hà Nội"
    },
    {
        "id":  "excel-s4-r59",
        "name":  "Nguyễn Hà Quang",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư kỹ thuật xây dựng- chuyên ngành Tài nguyên nước",
        "contractTerm":  "Thử việc 60 ngày (từ ngày 02/3/2026 -29/4/2026)",
        "contractSignedDate":  "",
        "phone":  "0386968948",
        "birthDate":  "1996-07-24",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "",
        "address":  "Thôn Phương Trạch, xã Vĩnh Thanh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Thôn Phương Trạch, xã Vĩnh Thanh, TP Hà Nội"
    },
    {
        "id":  "excel-s4-r60",
        "name":  "Nguyễn Thị Huệ",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân kế toán",
        "contractTerm":  "Thử việc 60 ngày (từ ngày 02/3/2026 -29/4/2026)",
        "contractSignedDate":  "",
        "phone":  "0969161747",
        "birthDate":  "1994-11-08",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "",
        "address":  "Thôn Ái Mộ, xã Phù Đổng, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Thôn Ái Mộ, xã Phù Đổng, TP Hà Nội"
    },
    {
        "id":  "excel-s4-r61",
        "name":  "Hoàng Phi Hùng",
        "gender":  "Nam",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Huấn luyện thể thao",
        "contractTerm":  "Thử việc 60 ngày (từ ngày 02/3/2026 -29/4/2026)",
        "contractSignedDate":  "",
        "phone":  "0337199610",
        "birthDate":  "2003-09-01",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "",
        "address":  "Thôn Hà Hương, xã Thư Lâm-TP HN",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Thôn Hà Hương, xã Thư Lâm-TP HN"
    },
    {
        "id":  "excel-s4-r62",
        "name":  "Phạm Huyền Trang",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân quản lý đất đai",
        "contractTerm":  "Thử việc 60 ngày (từ ngày 02/3/2026 -29/4/2026)",
        "contractSignedDate":  "",
        "phone":  "0373465427",
        "birthDate":  "2003-06-30",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "",
        "address":  "Thôn Lỗ Khê, xã Thư Lâm, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Thôn Lỗ Khê, xã Thư Lâm, TP Hà Nội"
    },
    {
        "id":  "excel-s4-r63",
        "name":  "Trần Như Quỳnh",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Công nghệ thực phẩm",
        "contractTerm":  "Thử việc 60 ngày (từ ngày 02/3/2026 -29/4/2026)",
        "contractSignedDate":  "",
        "phone":  "0338059614",
        "birthDate":  "2001-09-19",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "",
        "address":  "Số nhà 01, ngõ 11, thôn Bến Trung, xã Phúc Thịnh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: xã Dương Kinh, TP Hải Phòng"
    },
    {
        "id":  "excel-s4-r64",
        "name":  "Phạm Thu Hằng",
        "gender":  "Nữ",
        "departmentId":  "gpmb",
        "roleId":  "can-bo-gpmb",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân quản lý nhà nước",
        "contractTerm":  "",
        "contractSignedDate":  "",
        "phone":  "0978396918",
        "birthDate":  "2003-07-27",
        "start":  "",
        "salaryCoefficient":  "",
        "salaryGrade":  "",
        "salaryReviewDate":  "",
        "address":  "Thôn Châu Phong, xã Thư Lâm, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng GPMB; Chức vụ gốc: Nhân viên phòng GPMB; Quê quán: Thôn Châu Phong, xã Thư Lâm, TP Hà Nội"
    },
    {
        "id":  "excel-s5-r7",
        "name":  "Lê Hoàng",
        "gender":  "Nam",
        "departmentId":  "ha-tang",
        "roleId":  "truong-phong-ha-tang",
        "contract":  "Biên chế",
        "qualification":  "Đại học - Cử nhân kinh tế",
        "contractTerm":  "Không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0989209438",
        "birthDate":  "1983-02-07",
        "start":  "",
        "salaryCoefficient":  "3.99",
        "salaryGrade":  "6/9",
        "salaryReviewDate":  "2028-10-01",
        "address":  "thôn Phương Trạch, xã Vĩnh Thanh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng QLHT; Chức vụ gốc: Trưởng phòng QLHT; Quê quán: thôn Phương Trạch, xã Vĩnh Thanh, TP Hà Nội"
    },
    {
        "id":  "excel-s5-r8",
        "name":  "Đỗ Thị Thanh Huyền",
        "gender":  "Nữ",
        "departmentId":  "ha-tang",
        "roleId":  "can-bo-ha-tang",
        "contract":  "Biên chế",
        "qualification":  "Đại học - Cử nhân Kinh tế đối ngoại",
        "contractTerm":  "HĐLV không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0988564889",
        "birthDate":  "1982-09-29",
        "start":  "",
        "salaryCoefficient":  "3.33",
        "salaryGrade":  "4/9",
        "salaryReviewDate":  "2027-05-01",
        "address":  "Nguyên Khê-Phúc Thịnh-HN",
        "note":  "Nguồn Excel: Phòng QLHT; Chức vụ gốc: Viên chức phòng KHTH; Quê quán: Đan Tảo - Sóc Sơn - Hà Nội; Ngoại ngữ: x, x; Tin học: x, chuẩn Thông tư 03/2014/TT-BTTTT; Ngạch/CDNN: 01003"
    },
    {
        "id":  "excel-s5-r9",
        "name":  "Hà Đức Quân",
        "gender":  "Nam",
        "departmentId":  "ha-tang",
        "roleId":  "can-bo-ha-tang",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư XD công trình",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0934668021",
        "birthDate":  "1981-11-21",
        "start":  "",
        "salaryCoefficient":  "3",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2026-02-01",
        "address":  "Thôn Đại Đồng, xã Thiên Lộc, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng QLHT; Chức vụ gốc: Nhân viên phòng QLHT; Quê quán: Thôn Đại Đồng, xã Thiên Lộc, TP Hà Nội; Ngoại ngữ: Tiếng Anh, Bậc 2; Tin học: Chứng chỉ CNTT cơ bản"
    },
    {
        "id":  "excel-s5-r10",
        "name":  "Đặng Hùng Đông",
        "gender":  "Nam",
        "departmentId":  "ha-tang",
        "roleId":  "can-bo-ha-tang",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Cử nhân Luật kinh tế",
        "contractTerm":  "Đến 31/03/2026",
        "contractSignedDate":  "",
        "phone":  "0983866354",
        "birthDate":  "1983-11-04",
        "start":  "",
        "salaryCoefficient":  "2.67",
        "salaryGrade":  "2/9",
        "salaryReviewDate":  "2028-07-01",
        "address":  "Thôn Tiên Hội, xã Đông Anh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng QLHT; Chức vụ gốc: Nhân viên phòng QLHT; Quê quán: Thôn Tiên Hội, xã Đông Anh, TP Hà Nội; Đảng viên: Có"
    },
    {
        "id":  "excel-s5-r11",
        "name":  "Nguyễn Phương Nam",
        "gender":  "Nam",
        "departmentId":  "ha-tang",
        "roleId":  "can-bo-ha-tang",
        "contract":  "Hợp đồng chuyên môn",
        "qualification":  "Đại học - Kỹ sư kỹ thuật điện tử - viễn thông",
        "contractTerm":  "HĐLĐ không xác định thời hạn",
        "contractSignedDate":  "",
        "phone":  "0971715668",
        "birthDate":  "1990-11-24",
        "start":  "",
        "salaryCoefficient":  "3.00",
        "salaryGrade":  "3/9",
        "salaryReviewDate":  "2029-01-05",
        "address":  "xóm Dõng, xã Đông Anh, TP Hà Nội",
        "note":  "Nguồn Excel: Phòng QLHT; Chức vụ gốc: Nhân viên phòng QLHT; Quê quán: xóm Dõng, xã Đông Anh, TP Hà Nội"
    }
];

