create table if not exists public.kpi_account_login_events (
  id bigint generated by default as identity primary key,
  account_id text not null,
  session_token_hash text not null,
  logged_in_at timestamptz not null default now()
);

create index if not exists kpi_sync_sessions_last_seen_at_idx
  on public.kpi_sync_sessions (last_seen_at desc);

create index if not exists kpi_account_login_events_logged_in_at_idx
  on public.kpi_account_login_events (logged_in_at desc);

create index if not exists kpi_account_login_events_account_id_logged_in_at_idx
  on public.kpi_account_login_events (account_id, logged_in_at desc);

alter table public.kpi_account_login_events enable row level security;

revoke all on table public.kpi_account_login_events from anon, authenticated;
